var util = require("./util");

// see http://yuilibrary.com/yui/docs/api/classes/Node.html

exports['test Node Methods+Properties static'] = function() {
	util.assertCompletion("YUI().use('', function(Y) { Y.Node.", {
	    "start":{"line":0,"ch":35},
	    "end":{"line":0,"ch":35},
	    "isProperty":true,
	    "isObjectKey":false,
	    "completions":[{"name":"addMethod","type":"fn(name: string, fn: fn(), context: Object)","origin":"yui3"},
	                   {"name":"apply","type":"fn(this: ?, args: [?])","origin":"ecma5"},
	                   {"name":"bind","type":"fn(this: ?, args?: ?)","origin":"ecma5"},
	                   {"name":"call","type":"fn(this: ?, args?: ?)","origin":"ecma5"},
	                   {"name":"create","type":"fn(html: string, doc: Document) -> node.Node","origin":"yui3"},
	                   {"name":"getDOMNode","type":"fn(node: node.Node) -> Element","origin":"yui3"},
	                   {"name":"importMethod","type":"fn(host: Object, name: string, altName: string, context: Object)","origin":"yui3"},
	                   {"name":"one","type":"fn(node: string|Element) -> node.Node","origin":"yui3"},
	                   {"name":"plug","type":"fn(plugin: fn(), config: ?)","origin":"yui3"},
	                   {"name":"prototype","type":"node.Node.prototype","origin":"yui3"},
	                   {"name":"scrubVal","type":"fn(node: Element|[Element]) -> node.Node","origin":"yui3"},
	                   {"name":"unplug","type":"fn(plugin: fn())","origin":"yui3"},
	                   {"name":"ATTRS","type":"Object","origin":"yui3"},
	                   {"name":"DEFAULT_GETTER","type":"fn(name: string)","origin":"yui3"},
	                   {"name":"DEFAULT_SETTER","type":"fn(name: string, val: ?)","origin":"yui3"},
	                   {"name":"DOM_EVENTS","type":"?","origin":"yui3"},
	                   {"name":"NAME","type":"string","origin":"yui3"}
	                  ]
	});
}

exports['test Node Methods+Properties (not static) without var'] = function() {
  util.assertCompletion("YUI().use('', function(Y) { new Y.Node().", {
      "start":{"line":0,"ch":41},
      "end":{"line":0,"ch":41},
      "isProperty":true,
      "isObjectKey":false,
      "completions":[{"name":"addClass","type":"fn(className: string)","origin":"yui3"},
                     {"name":"addTarget","type":"fn(o: event_custom.EventTarget)","origin":"yui3"},
                     {"name":"after","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"all","type":"fn(selector: string) -> node.NodeList","origin":"yui3"},
                     {"name":"ancestor","type":"fn(fn: string, testSelf: bool, stopFn: string) -> node.Node","origin":"yui3"},
                     {"name":"ancestors","type":"fn(fn: string, testSelf: bool) -> node.NodeList","origin":"yui3"},
                     {"name":"append","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"appendChild","type":"fn(node: string|Element) -> node.Node","origin":"yui3"},
                     {"name":"appendTo","type":"fn(node: node.Node|string)","origin":"yui3"},
                     {"name":"before","type":"fn()","origin":"yui3"},
                     {"name":"blur","type":"fn()","origin":"yui3"},
                     {"name":"bubble","type":"fn(evt: event_custom.CustomEvent) -> bool","origin":"yui3"},
                     {"name":"children","type":"node.NodeList","origin":"yui3"},
                     {"name":"clearData","type":"fn(name: string)","origin":"yui3"},
                     {"name":"cloneNode","type":"fn(deep: bool) -> node.Node","origin":"yui3"},
                     {"name":"compareTo","type":"fn(refNode: Element) -> bool","origin":"yui3"},
                     {"name":"contains","type":"fn(needle: node.Node) -> bool","origin":"yui3"},
                     {"name":"create","type":"fn(html: string, doc: Document) -> node.Node","origin":"yui3"},
                     {"name":"createCaption","type":"fn()","origin":"yui3"},
                     {"name":"delegate","type":"fn(type: string, fn: fn(), spec: string, context: Object, args: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"destroy","type":"fn(recursivePurge: bool)","origin":"yui3"},
                     {"name":"detach","type":"fn(type: string|Object, fn: fn(), context: Object) -> event_custom.EventTarget","origin":"yui3"},
                     {"name":"detachAll","type":"fn(type: string)","origin":"yui3"},
                     {"name":"docHeight","type":"number","origin":"yui3"},
                     {"name":"docScrollX","type":"number","origin":"yui3"},
                     {"name":"docScrollY","type":"number","origin":"yui3"},
                     {"name":"docWidth","type":"number","origin":"yui3"},
                     {"name":"empty","type":"fn()","origin":"yui3"},
                     {"name":"fire","type":"fn(type: string|Object, arguments: Object) -> bool","origin":"yui3"},
                     {"name":"focus","type":"fn()","origin":"yui3"},
                     {"name":"for","type":"string","origin":"yui3"},
                     {"name":"generateID","type":"fn() -> string","origin":"yui3"},
                     {"name":"get","type":"fn(attr: string)","origin":"yui3"},
                     {"name":"getAttribute","type":"fn(name: string) -> string","origin":"yui3"},
                     {"name":"getAttrs","type":"fn(attrs: [?]) -> Object","origin":"yui3"},
                     {"name":"getComputedStyle","type":"fn(attr: string) -> string","origin":"yui3"},
                     {"name":"getDOMNode","type":"fn() -> Element","origin":"yui3"},
                     {"name":"getData","type":"fn(name: string) -> Object","origin":"yui3"},
                     {"name":"getElementsByTagName","type":"fn(tagName: string) -> node.NodeList","origin":"yui3"},
                     {"name":"getEvent","type":"fn(type: string, prefixed: string) -> event_custom.CustomEvent","origin":"yui3"},
                     {"name":"getHTML","type":"fn() -> string","origin":"yui3"},
                     {"name":"getStyle","type":"fn(attr: string) -> string","origin":"yui3"},
                     {"name":"getTargets","type":"fn()","origin":"yui3"},
                     {"name":"getX","type":"fn() -> number","origin":"yui3"},
                     {"name":"getXY","type":"fn() -> [?]","origin":"yui3"},
                     {"name":"getY","type":"fn() -> number","origin":"yui3"},
                     {"name":"hasAttribute","type":"fn(attribute: string) -> bool","origin":"yui3"},
                     {"name":"hasChildNodes","type":"fn() -> bool","origin":"yui3"},
                     {"name":"hasClass","type":"fn(className: string) -> bool","origin":"yui3"},
                     {"name":"hide","type":"fn(name: string, config: ?, callback: fn())","origin":"yui3"},
                     {"name":"inDoc","type":"fn(doc: node.Node) -> bool","origin":"yui3"},
                     {"name":"inRegion","type":"fn(node2: node.Node, all: bool, altRegion: Object) -> bool","origin":"yui3"},
                     {"name":"insert","type":"fn(content: string|node.Node, where: ?)","origin":"yui3"},
                     {"name":"insertBefore","type":"fn(newNode: string|Element, refNode: Element) -> node.Node","origin":"yui3"},
                     {"name":"intersect","type":"fn(node2: node.Node, altRegion: Object) -> Object","origin":"yui3"},
                     {"name":"invoke","type":"fn(method: string, args?: ?)","origin":"yui3"},
                     {"name":"load","type":"fn(url: string, selector: string, callback: fn())","origin":"yui3"},
                     {"name":"next","type":"fn(fn: string, all?: bool) -> node.Node","origin":"yui3"},
                     {"name":"on","type":"fn(type: string, fn: fn(e: event.DOMEventFacade), context?: ?, arg?: ?) -> event_custom.EventHandle|fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"once","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"onceAfter","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"one","type":"fn(selector: string) -> node.Node","origin":"yui3"},
                     {"name":"parseType","type":"fn(type: string, pre?: string) -> [?]","origin":"yui3"},
                     {"name":"prepend","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"previous","type":"fn(fn: string, all?: bool) -> node.Node","origin":"yui3"},
                     {"name":"publish","type":"fn(type: string, opts: {}) -> event_custom.CustomEvent","origin":"yui3"},
                     {"name":"purge","type":"fn(recurse: bool, type: string)","origin":"yui3"},
                     {"name":"region","type":"node.Node","origin":"yui3"},
                     {"name":"remove","type":"fn(destroy: bool)","origin":"yui3"},
                     {"name":"removeAttribute","type":"fn(attribute: string)","origin":"yui3"},
                     {"name":"removeChild","type":"fn(node: Element) -> node.Node","origin":"yui3"},
                     {"name":"removeClass","type":"fn(className: string)","origin":"yui3"},
                     {"name":"removeTarget","type":"fn(o: event_custom.EventTarget)","origin":"yui3"},
                     {"name":"replace","type":"fn(newNode: node.Node)","origin":"yui3"},
                     {"name":"replaceChild","type":"fn(node: string|Element, refNode: Element) -> node.Node","origin":"yui3"},
                     {"name":"replaceClass","type":"fn(oldClassName: string, newClassName: string)","origin":"yui3"},
                     {"name":"reset","type":"fn()","origin":"yui3"},
                     {"name":"scrollIntoView","type":"fn()","origin":"yui3"},
                     {"name":"select","type":"fn()","origin":"yui3"},
                     {"name":"set","type":"fn(attr: string, val: ?)","origin":"yui3"},
                     {"name":"setAttribute","type":"fn(name: string, value: string)","origin":"yui3"},
                     {"name":"setAttrs","type":"fn(attrMap: Object)","origin":"yui3"},
                     {"name":"setData","type":"fn(name: string, val: ?)","origin":"yui3"},
                     {"name":"setHTML","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"setStyle","type":"fn(attr: string, val: string|number)","origin":"yui3"},
                     {"name":"setStyles","type":"fn(hash: Object)","origin":"yui3"},
                     {"name":"setX","type":"fn(x: number)","origin":"yui3"},
                     {"name":"setXY","type":"fn(xy: [?])","origin":"yui3"},
                     {"name":"setY","type":"fn(y: number)","origin":"yui3"},
                     {"name":"show","type":"fn(name: string, config: ?, callback: fn())","origin":"yui3"},
                     {"name":"siblings","type":"fn(fn: string) -> node.NodeList","origin":"yui3"},
                     {"name":"simulate","type":"fn(type: string, options: Object)","origin":"yui3"},
                     {"name":"simulateGesture","type":"fn(name: string, options?: {}, cb?: fn(err: Error))","origin":"yui3"},
                     {"name":"submit","type":"fn()","origin":"yui3"},
                     {"name":"subscribe","type":"fn()","origin":"yui3"},
                     {"name":"swap","type":"fn(otherNode: node.Node)","origin":"yui3"},
                     {"name":"swapXY","type":"fn(otherNode: node.Node)","origin":"yui3"},
                     {"name":"test","type":"fn(selector: string) -> bool","origin":"yui3"},
                     {"name":"text","type":"string","origin":"yui3"},
                     {"name":"toString","type":"fn() -> string","origin":"yui3"},
                     {"name":"toggleClass","type":"fn(className: string, force: bool)","origin":"yui3"},
                     {"name":"toggleView","type":"fn(on?: bool, callback?: fn())","origin":"yui3"},
                     {"name":"transition","type":"fn(config: ?, callback: fn())","origin":"yui3"},
                     {"name":"unsubscribe","type":"fn()","origin":"yui3"},
                     {"name":"unsubscribeAll","type":"fn(type: string)","origin":"yui3"},
                     {"name":"unwrap","type":"fn()","origin":"yui3"},
                     {"name":"viewportRegion","type":"node.Node","origin":"yui3"},
                     {"name":"winHeight","type":"number","origin":"yui3"},
                     {"name":"winWidth","type":"number","origin":"yui3"},
                     {"name":"wrap","type":"fn(html: string)","origin":"yui3"}

                    ]
  });
}

exports['test Node Methods+Properties (not static)'] = function() {
  util.assertCompletion("YUI().use('', function(Y) { var node = new Y.Node(); node.", {
      "start":{"line":0,"ch":58},
      "end":{"line":0,"ch":58},
      "isProperty":true,
      "isObjectKey":false,
      "completions":[{"name":"addClass","type":"fn(className: string)","origin":"yui3"},
                     {"name":"addTarget","type":"fn(o: event_custom.EventTarget)","origin":"yui3"},
                     {"name":"after","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"all","type":"fn(selector: string) -> node.NodeList","origin":"yui3"},
                     {"name":"ancestor","type":"fn(fn: string, testSelf: bool, stopFn: string) -> node.Node","origin":"yui3"},
                     {"name":"ancestors","type":"fn(fn: string, testSelf: bool) -> node.NodeList","origin":"yui3"},
                     {"name":"append","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"appendChild","type":"fn(node: string|Element) -> node.Node","origin":"yui3"},
                     {"name":"appendTo","type":"fn(node: node.Node|string)","origin":"yui3"},
                     {"name":"before","type":"fn()","origin":"yui3"},
                     {"name":"blur","type":"fn()","origin":"yui3"},
                     {"name":"bubble","type":"fn(evt: event_custom.CustomEvent) -> bool","origin":"yui3"},
                     {"name":"children","type":"node.NodeList","origin":"yui3"},
                     {"name":"clearData","type":"fn(name: string)","origin":"yui3"},
                     {"name":"cloneNode","type":"fn(deep: bool) -> node.Node","origin":"yui3"},
                     {"name":"compareTo","type":"fn(refNode: Element) -> bool","origin":"yui3"},
                     {"name":"contains","type":"fn(needle: node.Node) -> bool","origin":"yui3"},
                     {"name":"create","type":"fn(html: string, doc: Document) -> node.Node","origin":"yui3"},
                     {"name":"createCaption","type":"fn()","origin":"yui3"},
                     {"name":"delegate","type":"fn(type: string, fn: fn(), spec: string, context: Object, args: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"destroy","type":"fn(recursivePurge: bool)","origin":"yui3"},
                     {"name":"detach","type":"fn(type: string|Object, fn: fn(), context: Object) -> event_custom.EventTarget","origin":"yui3"},
                     {"name":"detachAll","type":"fn(type: string)","origin":"yui3"},
                     {"name":"docHeight","type":"number","origin":"yui3"},
                     {"name":"docScrollX","type":"number","origin":"yui3"},
                     {"name":"docScrollY","type":"number","origin":"yui3"},
                     {"name":"docWidth","type":"number","origin":"yui3"},
                     {"name":"empty","type":"fn()","origin":"yui3"},
                     {"name":"fire","type":"fn(type: string|Object, arguments: Object) -> bool","origin":"yui3"},
                     {"name":"focus","type":"fn()","origin":"yui3"},
                     {"name":"for","type":"string","origin":"yui3"},
                     {"name":"generateID","type":"fn() -> string","origin":"yui3"},
                     {"name":"get","type":"fn(attr: string)","origin":"yui3"},
                     {"name":"getAttribute","type":"fn(name: string) -> string","origin":"yui3"},
                     {"name":"getAttrs","type":"fn(attrs: [?]) -> Object","origin":"yui3"},
                     {"name":"getComputedStyle","type":"fn(attr: string) -> string","origin":"yui3"},
                     {"name":"getDOMNode","type":"fn() -> Element","origin":"yui3"},
                     {"name":"getData","type":"fn(name: string) -> Object","origin":"yui3"},
                     {"name":"getElementsByTagName","type":"fn(tagName: string) -> node.NodeList","origin":"yui3"},
                     {"name":"getEvent","type":"fn(type: string, prefixed: string) -> event_custom.CustomEvent","origin":"yui3"},
                     {"name":"getHTML","type":"fn() -> string","origin":"yui3"},
                     {"name":"getStyle","type":"fn(attr: string) -> string","origin":"yui3"},
                     {"name":"getTargets","type":"fn()","origin":"yui3"},
                     {"name":"getX","type":"fn() -> number","origin":"yui3"},
                     {"name":"getXY","type":"fn() -> [?]","origin":"yui3"},
                     {"name":"getY","type":"fn() -> number","origin":"yui3"},
                     {"name":"hasAttribute","type":"fn(attribute: string) -> bool","origin":"yui3"},
                     {"name":"hasChildNodes","type":"fn() -> bool","origin":"yui3"},
                     {"name":"hasClass","type":"fn(className: string) -> bool","origin":"yui3"},
                     {"name":"hide","type":"fn(name: string, config: ?, callback: fn())","origin":"yui3"},
                     {"name":"inDoc","type":"fn(doc: node.Node) -> bool","origin":"yui3"},
                     {"name":"inRegion","type":"fn(node2: node.Node, all: bool, altRegion: Object) -> bool","origin":"yui3"},
                     {"name":"insert","type":"fn(content: string|node.Node, where: ?)","origin":"yui3"},
                     {"name":"insertBefore","type":"fn(newNode: string|Element, refNode: Element) -> node.Node","origin":"yui3"},
                     {"name":"intersect","type":"fn(node2: node.Node, altRegion: Object) -> Object","origin":"yui3"},
                     {"name":"invoke","type":"fn(method: string, args?: ?)","origin":"yui3"},
                     {"name":"load","type":"fn(url: string, selector: string, callback: fn())","origin":"yui3"},
                     {"name":"next","type":"fn(fn: string, all?: bool) -> node.Node","origin":"yui3"},
                     {"name":"on","type":"fn(type: string, fn: fn(e: event.DOMEventFacade), context?: ?, arg?: ?) -> event_custom.EventHandle|fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"once","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"onceAfter","type":"fn(type: string, fn: fn(), context?: Object, arg?: ?) -> event_custom.EventHandle","origin":"yui3"},
                     {"name":"one","type":"fn(selector: string) -> node.Node","origin":"yui3"},
                     {"name":"parseType","type":"fn(type: string, pre?: string) -> [?]","origin":"yui3"},
                     {"name":"prepend","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"previous","type":"fn(fn: string, all?: bool) -> node.Node","origin":"yui3"},
                     {"name":"publish","type":"fn(type: string, opts: {}) -> event_custom.CustomEvent","origin":"yui3"},
                     {"name":"purge","type":"fn(recurse: bool, type: string)","origin":"yui3"},
                     {"name":"region","type":"node.Node","origin":"yui3"},
                     {"name":"remove","type":"fn(destroy: bool)","origin":"yui3"},
                     {"name":"removeAttribute","type":"fn(attribute: string)","origin":"yui3"},
                     {"name":"removeChild","type":"fn(node: Element) -> node.Node","origin":"yui3"},
                     {"name":"removeClass","type":"fn(className: string)","origin":"yui3"},
                     {"name":"removeTarget","type":"fn(o: event_custom.EventTarget)","origin":"yui3"},
                     {"name":"replace","type":"fn(newNode: node.Node)","origin":"yui3"},
                     {"name":"replaceChild","type":"fn(node: string|Element, refNode: Element) -> node.Node","origin":"yui3"},
                     {"name":"replaceClass","type":"fn(oldClassName: string, newClassName: string)","origin":"yui3"},
                     {"name":"reset","type":"fn()","origin":"yui3"},
                     {"name":"scrollIntoView","type":"fn()","origin":"yui3"},
                     {"name":"select","type":"fn()","origin":"yui3"},
                     {"name":"set","type":"fn(attr: string, val: ?)","origin":"yui3"},
                     {"name":"setAttribute","type":"fn(name: string, value: string)","origin":"yui3"},
                     {"name":"setAttrs","type":"fn(attrMap: Object)","origin":"yui3"},
                     {"name":"setData","type":"fn(name: string, val: ?)","origin":"yui3"},
                     {"name":"setHTML","type":"fn(content: string|node.Node)","origin":"yui3"},
                     {"name":"setStyle","type":"fn(attr: string, val: string|number)","origin":"yui3"},
                     {"name":"setStyles","type":"fn(hash: Object)","origin":"yui3"},
                     {"name":"setX","type":"fn(x: number)","origin":"yui3"},
                     {"name":"setXY","type":"fn(xy: [?])","origin":"yui3"},
                     {"name":"setY","type":"fn(y: number)","origin":"yui3"},
                     {"name":"show","type":"fn(name: string, config: ?, callback: fn())","origin":"yui3"},
                     {"name":"siblings","type":"fn(fn: string) -> node.NodeList","origin":"yui3"},
                     {"name":"simulate","type":"fn(type: string, options: Object)","origin":"yui3"},
                     {"name":"simulateGesture","type":"fn(name: string, options?: {}, cb?: fn(err: Error))","origin":"yui3"},
                     {"name":"submit","type":"fn()","origin":"yui3"},
                     {"name":"subscribe","type":"fn()","origin":"yui3"},
                     {"name":"swap","type":"fn(otherNode: node.Node)","origin":"yui3"},
                     {"name":"swapXY","type":"fn(otherNode: node.Node)","origin":"yui3"},
                     {"name":"test","type":"fn(selector: string) -> bool","origin":"yui3"},
                     {"name":"text","type":"string","origin":"yui3"},
                     {"name":"toString","type":"fn() -> string","origin":"yui3"},
                     {"name":"toggleClass","type":"fn(className: string, force: bool)","origin":"yui3"},
                     {"name":"toggleView","type":"fn(on?: bool, callback?: fn())","origin":"yui3"},
                     {"name":"transition","type":"fn(config: ?, callback: fn())","origin":"yui3"},
                     {"name":"unsubscribe","type":"fn()","origin":"yui3"},
                     {"name":"unsubscribeAll","type":"fn(type: string)","origin":"yui3"},
                     {"name":"unwrap","type":"fn()","origin":"yui3"},
                     {"name":"viewportRegion","type":"node.Node","origin":"yui3"},
                     {"name":"winHeight","type":"number","origin":"yui3"},
                     {"name":"winWidth","type":"number","origin":"yui3"},
                     {"name":"wrap","type":"fn(html: string)","origin":"yui3"}
                    ]
  });
}

if (module == require.main) require("test").run(exports);